/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProblemsWithUseEffectRouteImport } from './routes/problems-with-use-effect'
import { Route as InfiniteQueryRouteImport } from './routes/infinite-query'
import { Route as DebouncedSearchRouteImport } from './routes/debounced-search'
import { Route as BasicQueryRouteImport } from './routes/basic-query'
import { Route as IndexRouteImport } from './routes/index'

const ProblemsWithUseEffectRoute = ProblemsWithUseEffectRouteImport.update({
  id: '/problems-with-use-effect',
  path: '/problems-with-use-effect',
  getParentRoute: () => rootRouteImport,
} as any)
const InfiniteQueryRoute = InfiniteQueryRouteImport.update({
  id: '/infinite-query',
  path: '/infinite-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DebouncedSearchRoute = DebouncedSearchRouteImport.update({
  id: '/debounced-search',
  path: '/debounced-search',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicQueryRoute = BasicQueryRouteImport.update({
  id: '/basic-query',
  path: '/basic-query',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-query': typeof BasicQueryRoute
  '/debounced-search': typeof DebouncedSearchRoute
  '/infinite-query': typeof InfiniteQueryRoute
  '/problems-with-use-effect': typeof ProblemsWithUseEffectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-query': typeof BasicQueryRoute
  '/debounced-search': typeof DebouncedSearchRoute
  '/infinite-query': typeof InfiniteQueryRoute
  '/problems-with-use-effect': typeof ProblemsWithUseEffectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-query': typeof BasicQueryRoute
  '/debounced-search': typeof DebouncedSearchRoute
  '/infinite-query': typeof InfiniteQueryRoute
  '/problems-with-use-effect': typeof ProblemsWithUseEffectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic-query'
    | '/debounced-search'
    | '/infinite-query'
    | '/problems-with-use-effect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic-query'
    | '/debounced-search'
    | '/infinite-query'
    | '/problems-with-use-effect'
  id:
    | '__root__'
    | '/'
    | '/basic-query'
    | '/debounced-search'
    | '/infinite-query'
    | '/problems-with-use-effect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicQueryRoute: typeof BasicQueryRoute
  DebouncedSearchRoute: typeof DebouncedSearchRoute
  InfiniteQueryRoute: typeof InfiniteQueryRoute
  ProblemsWithUseEffectRoute: typeof ProblemsWithUseEffectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/problems-with-use-effect': {
      id: '/problems-with-use-effect'
      path: '/problems-with-use-effect'
      fullPath: '/problems-with-use-effect'
      preLoaderRoute: typeof ProblemsWithUseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infinite-query': {
      id: '/infinite-query'
      path: '/infinite-query'
      fullPath: '/infinite-query'
      preLoaderRoute: typeof InfiniteQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debounced-search': {
      id: '/debounced-search'
      path: '/debounced-search'
      fullPath: '/debounced-search'
      preLoaderRoute: typeof DebouncedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-query': {
      id: '/basic-query'
      path: '/basic-query'
      fullPath: '/basic-query'
      preLoaderRoute: typeof BasicQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicQueryRoute: BasicQueryRoute,
  DebouncedSearchRoute: DebouncedSearchRoute,
  InfiniteQueryRoute: InfiniteQueryRoute,
  ProblemsWithUseEffectRoute: ProblemsWithUseEffectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
